#!/bin/bash
# Author: @FershoUno
# Build DEB from ParrotSec/parrot-interface (browser only)

#set -e

### CONFIG ###
NAME="plurios-firefox-profiles"
VERSION="1.0.0"
ARCH="all"
MAINTAINER="Fersho Uno <fersh0un0@gmail.com>"
SECTION="web"

REPO_URL="https://github.com/ParrotSec/parrot-interface.git"
SRC_DIR="parrot-interface"
BROWSER_DIR="browser"

WORKDIR="${NAME}_${VERSION}_${ARCH}"

# Archivos a copiar
FILES=(
  "00parrot.js"
  "firefox.js"
  "policies.json"
)

# Líneas a eliminar (por archivo)
REMOVE_LINES_00PLURIOS="8,9,10,11"
REMOVE_LINES_FIREFOX="10,11,12,13,14,22"
REMOVE_LINES_POLICIES=""

# Reemplazar en firefox.js 00plurios.js
SEARCH_TEXT="Parrot OS"
REPLACE_TEXT="PluriOS"

# Reemplazar en policies.json
JSON_CHANGES=(
  '.policies.Homepage.URL = "file:///usr/share/plurios/html/index.html"'
  '.policies.DontCheckDefaultBrowser = false'
  '.policies.DisableTelemetry = true'

  '.policies.PopupBlocking.Allow = [
    "https://plurios.openit.dev",
    "https://t.me/+5jCOmzWV3JE1OTkx"
  ]'

  '.policies.SupportMenu.Title = "PluriOS Support"'
  '.policies.SupportMenu.URL = "https://t.me/+5jCOmzWV3JE1OTkx"'
)

### LIMPIEZA ###
rm -rf "$WORKDIR" "$SRC_DIR" *.deb

### CLONAR REPO ###
git clone --depth=1 "$REPO_URL"

### CREAR ESTRUCTURA ###
mkdir -p \
  "$WORKDIR/etc/firefox/policies" \
  "$WORKDIR/etc/firefox-esr/policies"

### COPIAR DEBIAN ###
cp -r DEBIAN "$WORKDIR/"
cp -r usr/ "$WORKDIR/"

### COPIAR ARCHIVOS ###
for file in "${FILES[@]}"; do
 if [[ "$file" == "00parrot.js" ]]; then
	dest="00plurios.js"
 else
	dest="$file"
 fi
 if [[ "$file" == "policies.json" ]];then
	cp "$SRC_DIR/$BROWSER_DIR/$file" "$WORKDIR/etc/firefox/policies/$file"
	cp "$SRC_DIR/$BROWSER_DIR/$file" "$WORKDIR/etc/firefox-esr/policies/$file"
 else
  	cp "$SRC_DIR/$BROWSER_DIR/$file" "$WORKDIR/etc/firefox/$dest"
  	cp "$SRC_DIR/$BROWSER_DIR/$file" "$WORKDIR/etc/firefox-esr/$dest"
 fi
done

remove_lines() {
  local file="$1"
  local lines="$2"

  [ -z "$lines" ] && return

  # Convertir "15,70,150" → "15d;70d;150d"
  local sed_expr
  sed_expr=$(echo "$lines" | sed 's/,/d;/g')d

  sed -i "$sed_expr" "$file"
}

replace_text() {

  local file="$1"
  sed -i "s/${SEARCH_TEXT}/${REPLACE_TEXT}/g" "$file"
}

modify_json() {
  local file="$1"
  [ ! -f "$file" ] && return

  local tmp
  tmp="$(mktemp)"

  cp "$file" "$tmp"

  for expr in "${JSON_CHANGES[@]}"; do
    jq "$expr" "$tmp" > "${tmp}.new" && mv "${tmp}.new" "$tmp"
  done

  mv "$tmp" "$file"
}

### MODIFICACIONES ###
for dir in firefox firefox-esr; do
  remove_lines "$WORKDIR/etc/$dir/00plurios.js" "$REMOVE_LINES_00PLURIOS"
  remove_lines "$WORKDIR/etc/$dir/firefox.js" "$REMOVE_LINES_FIREFOX"
  remove_lines "$WORKDIR/etc/$dir/policies/policies.json" "$REMOVE_LINES_POLICIES"

  replace_text "$WORKDIR/etc/$dir/00plurios.js"
  replace_text "$WORKDIR/etc/$dir/firefox.js"
  modify_json "$WORKDIR/etc/$dir/policies/policies.json"
done

### ACTUALIZAR CONTROL ###
SIZE=$(du -ks --exclude=DEBIAN "$WORKDIR" | awk '{print $1}')

sed -i "s/CHANGE_NAME/$NAME/g" "$WORKDIR/DEBIAN/control"
sed -i "s/CHANGE_VERSION/$VERSION/g" "$WORKDIR/DEBIAN/control"
sed -i "s/CHANGE_ARCH/$ARCH/g" "$WORKDIR/DEBIAN/control"
sed -i "s/CHANGE_MAINTAINER/$MAINTAINER/g" "$WORKDIR/DEBIAN/control"
sed -i "s/CHANGE_SECTION/$SECTION/g" "$WORKDIR/DEBIAN/control"
sed -i "s/CHANGE_SIZE/$SIZE/g" "$WORKDIR/DEBIAN/control"

### PERMISOS

find "$WORKDIR" -type d -exec chmod 755 {} +
find "$WORKDIR" -type f -exec chmod 644 {} +

### BUILD CON FAKEROOT ###
fakeroot dpkg-deb --build "$WORKDIR"

echo "✔ Paquete generado: ${WORKDIR}.deb"
